---
title: "obat_analysis_visuals"
output: html_document
---

```{r, include = FALSE}
library(tidyverse)

obat <- read_csv("C:/Users/hebers/Downloads/OBAT Project_DataAnalysis.csv")
```

# Initial visuals

```{r, echo = FALSE}
p.famplan <- ggplot(obat, aes(`Family planning missing`)) + geom_bar()
p.famplan

p.famplanfu <- ggplot(obat, aes(`Family Planning Follow Up`)) + geom_bar()
p.famplanfu

p.papsm <- ggplot(obat, aes(`Pap smear missing`)) + geom_bar()
p.papsm

p.papsmfu <- ggplot(obat, aes(`Pap smear Follow Up`)) + geom_bar()
p.papsmfu

p.prep <- ggplot(obat, aes(`PrEP missing`)) + geom_bar()
p.prep

p.prepfu <- ggplot(obat, aes(`PrEP Follow Up`)) + geom_bar()
p.prepfu

age.hist <- hist(obat$Age)
age.hist

p.race <- ggplot(obat, aes(Race)) + geom_bar()
p.race

p.eth <- ggplot(obat, aes(Ethnicity)) + geom_bar()
p.eth

p.lang <- ggplot(obat, aes(Langauge)) + geom_bar()
p.lang

p.mar <- ggplot(obat, aes(`Martial status`)) + geom_bar()
p.mar
```

# Data transformation

```{r}
# Fixing ethnicity data
obat$Ethnicity <- ifelse(obat$Ethnicity == "Puerto Rican", "Hispanic or Latino", 
                         ifelse(obat$Ethnicity == "Declined", "Declined", 
                                ifelse(obat$Ethnicity == "Hispanic or Latino", "Hispanic or Latino", 
                                       "Not Hispanic or Latino")))
obat$Ethnicity <- relevel(as.factor(obat$Ethnicity), ref = "Not Hispanic or Latino")
# Binary data
obat2 <- obat
obat2$`Family planning missing` <- ifelse(obat$`Family planning missing` == "Yes", 
                                          1, 0)
obat2$`Pap smear missing` <- ifelse(obat$`Pap smear missing` == "Yes", 1, 0)
obat2$`PrEP missing` <- ifelse(obat$`PrEP missing` == "Yes", 1, 0)

obat2$`Pap smear Follow Up` <- ifelse(obat$`Pap smear Follow Up` == "No", 0, 1)
obat2$`PrEP Follow Up` <- ifelse(obat$`PrEP Follow Up` == "No", 0, 1)

# Age limit
obat45 <- obat2 %>% 
  filter(Age <= 45)
```

# Models, missing services

```{r}
agerace.famp45 <- glm(`Family planning missing` ~ Age + Ethnicity, family = "binomial", 
                    data = obat45)
summary(agerace.famp45)

agerace.papsm <- glm(`Pap smear missing` ~ Age + Ethnicity, family = "binomial", 
                     data = obat2)
summary(agerace.papsm)

agerace.prep <- glm(`PrEP missing` ~ Age, family = "binomial", data = obat2)
summary(agerace.prep)
```

# Models, follow-up appointments

```{r}
# Family planning follow-up
obatfpfu <- obat %>% 
  filter(Age <= 45) %>% 
  filter(`Family planning missing` == "Yes")
table(obatfpfu$`Family Planning Follow Up`, obatfpfu$Age)
table(obatfpfu$`Family Planning Follow Up`, obatfpfu$Race)
obatfpfu_n <- obatfpfu %>% filter(`Family Planning Follow Up` == "No")
obatfpfu_y <- obatfpfu %>% filter(`Family Planning Follow Up` == "Yes")
obatfpfu_p <- obatfpfu %>% filter(`Family Planning Follow Up` == "Pregnant")
mean(obatfpfu_n$Age)
mean(obatfpfu_y$Age)
mean(obatfpfu_p$Age)

obatfpfum <- obatfpfu
obatfpfum$`Family Planning Follow Up` <- ifelse(obatfpfum$`Family Planning Follow Up` 
                                                == "No", 0, 1)
fpfu <- glm(`Family Planning Follow Up` ~ Age, family = "binomial", data = obatfpfum)
summary(fpfu)
```

```{r}
# Pap smear follow-up
# NOTE: Discussed is counted as a "Yes" here
psfu <- glm(`Pap smear Follow Up` ~ Age + Ethnicity, family = "binomial", data = obat2)
summary(psfu)
```

```{r}
# PrEP follow-up
# There is no variation in PrEP follow-up data, so no model is needed
```

# Missing more than one service

```{r}
table(obat$`Pap smear missing`, obat$`PrEP missing`)
```

```{r}
table(obat45$`Family planning missing`, obat45$`Pap smear missing`)

fpps <- glm(`Family planning missing` ~ `Pap smear missing`, family = "binomial", 
            data = obat45)
summary(fpps)
```

```{r}
table(obat45$`Family planning missing`, obat45$`PrEP missing`)
```

